{
 "title": "Wazuh Geral",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\r\n<br>\r\n<center><img width=\"100\" src=\"https://upload.wikimedia.org/wikipedia/commons/1/13/Wazuh-orig.png\">\r\n<center><img width=\"500\" src=\"https://upload.wikimedia.org/wikipedia/commons/c/c3/Wazuh-Logo-2022.png\">"
   }
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "FB - Servidores Linux DC" },
     "host": { "filter": "fbdclnxwazuh" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "FB - Servidores Linux DC" },
     "host": { "filter": "fbdclnxwazuh" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "FB - Servidores Linux DC" },
     "host": { "filter": "fbdclnxwazuh" },
     "item": { "filter": "/: Space utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\r\n<center><h1>Active-Response</h1>\r\n<center><p>Rules: 651 e 657</p>"
   }
  },
  {
   "title": "Rule 651 e 657",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (651 OR 657)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Attack Types Identified",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:(5763 OR 5712 OR 60204 OR 5104)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VirusTotal: Number of viruses found",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "location: virustotal AND data.virustotal.malicious: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 8, "x": 9, "y": 9 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "data.vulnerability.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Critical",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "data.vulnerability.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: High",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "data.vulnerability.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Medium",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "data.vulnerability.status",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Low",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "location: syscheck AND syscheck.event: added AND syscheck.audit.user.name: *.* AND NOT syscheck.path: HKEY* AND NOT syscheck.path: *queue*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Modified",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "location: syscheck AND syscheck.event: modified AND syscheck.audit.user.name: *.* AND NOT syscheck.path: HKEY* AND NOT syscheck.path: *queue*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "location: syscheck AND syscheck.event: deleted AND syscheck.audit.user.name: *.* AND NOT syscheck.path: HKEY* AND NOT syscheck.path: *queue*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Types of web attack identified",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.id:(31533 OR 31104 OR 31103 OR 31168)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rule: 92653 - RDP Authentication",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (92653)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules: (5715, 5760) - SSH authentication",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (5715 OR 5760)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rule: 5402 e 5404- sudo acess",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (5402 OR 5404)",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Rules: (31533) - DDoS Detected",
   "type": "table",
   "description": "High amount of POST requests in a small period of time (likely bot).",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (31533)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules: (31104) - LFI",
   "type": "table",
   "description": "Common web attack.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (31104)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules: (31103) - SQL Inject Detected",
   "type": "table",
   "description": "SQL injection attempt.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (31103)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules: (31168) - Shell Shock Detected",
   "type": "table",
   "description": "Shellshock attack detected\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "rule.id: (31168)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Brute Force",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
     "options": {
      "content": "<br>\r\n<center><h1>BRUTE FORCE</h1>\r\n<center><p>Rules:60204 - Multiple Windows logon failures.</p> "
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
     "options": {
      "content": "<br>\r\n<center><h1>BRUTE FORCE</h1>\r\n<center><p>Rules:5763 e 5712 - brute force trying to get access to the system. Authentication failed or Non Existent User.</p> "
     }
    },
    {
     "title": "Rule 60204\t",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:60204",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rule 60204",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data.win.eventdata.targetDomainName",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "logs" }
       ],
       "query": "rule.id:60204",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rule 5763 ",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.srcip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:( 5763 OR 5712 )",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rule 5763",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data.win.eventdata.targetDomainName",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "logs" }
       ],
       "query": "rule.id:( 5763 OR 5712 )",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Ver Depois",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rule 92657",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id: 92657 AND NOT data.win.eventdata.ipAddress: null AND NOT data.win.eventdata.ipAddress: 127.0.0.1 AND data.win.eventdata.targetUserName: *.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rule 92657 ",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data.win.eventdata.targetDomainName",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "logs" }
       ],
       "query": "rule.id:92657 AND NOT data.win.eventdata.ipAddress: null AND NOT data.win.eventdata.ipAddress: 127.0.0.1 AND data.win.eventdata.targetUserName: *.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
     "options": {
      "content": "<br>\r\n<center><h1>REMOTE DESKTOP</h1>\r\n<center><p>Rule 92657 - Successful Remote Logon Detected.</p> "
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
     "options": {
      "content": "<br>\r\n<center><h1>TRAFFIC SHAPING</h1>\r\n<center><p>Rules:Rule 101103 - Sysmon - Event 3: Network connection.</p> "
     }
    },
    {
     "title": "Rule 101103 - Sysmon - Event 3: Network connection.",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent.name",
         "id": "4",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "rule.id:101103 ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Rule 101103 - Sysmon - Event 3: Network connection.",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "data.win.eventdata.ipAddress",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "data.win.eventdata.targetDomainName",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "logs" }
       ],
       "query": "rule.id:101103 ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}